# -*- coding: utf-8 -*-
"""Criacao de ambiente Virtual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7DmObDbg-W7Z66XhlIo48tL2NPo10xU

Ambientes virtuais criam "uma cópia" do Python e permitem  instalação de pacotes a ela restritos

###Criar um ambiente virtual


```
C:> cd BASE
C:> python -m venv nome_ambiente
```

###Ativar o ambiente virtual###

**Windows:**

```
c:> cd BASE
c:> nome_ambiente\Scripts\activate.bat
```

**Linux:**

```
$ cd BASE
$ source nome_ambiente/bin/activate`
```

###Desativar o ambiente virtual###

**Windows:**

```
c:> cd BASE
c:> nome_ambiente\Scripts\deactivate.bat
```

**Linux:**

```
$ exit
```

### Help do venv

```
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
            [--upgrade] [--without-pip] [--prompt PROMPT]
            ENV_DIR [ENV_DIR ...]

Creates virtual Python environments in one or more target directories.

positional arguments:
  ENV_DIR               A directory to create the environment in.

optional arguments:
  -h, --help            show this help message and exit --system-site-packages
                        Give the virtual environment access to the system
                        site-packages dir.
  --symlinks            Try to use symlinks rather than copies, when symlinks
                        are not the default for the platform.
  --copies              Try to use copies rather than symlinks, even when
                        symlinks are the default for the platform.
  --clear               Delete the contents of the environment directory if it
                        already exists, before environment creation.
  --upgrade             Upgrade the environment directory to use this version
                        of Python, assuming Python has been upgraded in-place.
  --without-pip         Skips installing or upgrading pip in the virtual
                        environment (pip is bootstrapped by default)
  --prompt PROMPT       Provides an alternative prompt prefix for this
                        environment.

Once an environment has been created, you may wish to activate it, e.g. by
sourcing an activate script in its bin directory.
```
"""